# Generated by Django 4.2.13 on 2024-07-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_options_product_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['tittle'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
